### ISSUE TITLE
mvn打包后，jar怎么部署到tomcat上啊。启动不了呀。

### ISSUE THREAD

**Issue by daberber** [hs-web/hsweb3-demo#26]

**Comment by zhou-hao** [comment]
直接使用命令: `java -jar hsweb3-demo.jar` 启动即可

**Comment by daberber** [comment]
![image](https://user-images.githubusercontent.com/13213408/47142720-23403b80-d2f6-11e8-8e3c-45016981a837.png)
谢谢。但是运行之后却是404
开发模式可以起来

**Comment by zhou-hao** [comment]
#27

**Comment by daberber** [comment]
感谢大神啊~这个框架真的是国内良心啊。请问有交流群么。

**Comment by zhou-hao** [comment]
@daberber  QQ群 ：515649185
