### ISSUE TITLE
请问一下后台使用教程在哪？

### ISSUE THREAD

**Issue by AsherAngelo** [hs-web/hsweb3-demo#29]
采用mysql启动版本必须是5.7以上
alter database hsweb3 character set latin1;要不然会超过1000的名称，设置好后项目启动没有问题。
-----
以上没用，就是想问一下作者请问一下后台使用教程在哪？谢谢

**Comment by zhou-hao** [comment]
贴一下错误原因。hsweb-framework的问题可以在[这里提](https://github.com/hs-web/hsweb-framework/issues/new/choose). 使用教程暂时没有，文档正在完善。
